# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0012_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImioAesMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('meal_file', models.FileField(help_text='Supported file formats: csv, json', upload_to=b'aes_meal', verbose_name='AES Meal file')),
                ('users', models.ManyToManyField(blank=True, to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Aes meal importer and serve in wcs',
            },
        ),
    ]
