# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_aes_meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imioaesmeal',
            name='ignore_types',
            field=models.CharField(default=b'', max_length=128, verbose_name='Types to ignore'),
        ),
        migrations.AddField(
            model_name='imioaesmeal',
            name='nothing',
            field=models.BooleanField(default=False, verbose_name='Authorize to select "nothing" item'),
        ),
        migrations.AlterField(
            model_name='imioaesmeal',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_imioaesmeal_users_+', related_query_name='+', to='base.ApiUser'),
        ),
    ]
