# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_aes_meal', '0003_auto_20190729_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imioaesmeal',
            name='ignore_types',
            field=models.CharField(blank=True, default=b'', max_length=128, verbose_name='Types to ignore'),
        ),
    ]
