# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_aes_meal', '0006_imioaesmeal_multi_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imioaesmeal',
            name='nothing',
            field=models.BooleanField(default=False, verbose_name='Authorize to select "nothing" item'),
        ),
    ]
